Two update hooks to remove old News and Final Orders
lfucg/lexingtonky.gov pull request #418
Opened 2023-07-12 14:47 UTC by JMStewart00

## Summary / Approach

Add two update hooks to run with `drush updb` that will remove old news and final orders from the DB.
Thinking ahead, the function added gives ability to reuse the logic needed.

## Testing Instruction(s)

If the hooks run automatically on the multidev sites, which I'm assuming they do, just visit and see if the items were deleted. Should be messages in the logs that it ran as well. 

If not you'll need to visit, update.php

## Screenshots

![Screenshot 2023-07-12 at 10 46 18 AM](https://github.com/lfucg/lexingtonky.gov/assets/27921423/f0b56737-6cae-46b7-9230-e5689225df99)
Showing the items are all gone.

## Metadata

| Question | Answer |
|----------|--------|
| Did you perform a self-review of this PR? | yes
| Documentation reflects changes? | n/a
| Unit/Functional tests reflect changes? | n/a
| Did you perform browser testing? | n/a
| Did you provide detail in the summary on how and where to test this branch? | yes
| Relevant links | [LG-74](https://apaxsoftware.atlassian.net/browse/LG-74)

2023-07-12 14:57 UTC, TaylorAkin commented
[![Visit Site](https://raw.githubusercontent.com/pantheon-systems/terminus-build-tools-plugin/master/assets/images/visit-site-36.png)](https://pr-418-lexky-d8.pantheonsite.io/)

Created multidev environment [pr-418](https://dashboard.pantheon.io/sites/085efc9d-6f4f-4d02-a80b-9d5cf086a982#pr-418) for lexky-d8.

2023-07-12 15:26 UTC, JMStewart00 commented
@TaylorAkin due to the amount of nodes in these updates I might need to add some custom batch handling so we don't timeout which is why the build failed I'm assuming.

2023-07-12 20:20 UTC, JMStewart00 commented
@TaylorAkin I believe I have this ready to go at this point. Batching is actually baked into the update hooks. Which is kinda nice.

2023-07-13 18:49 UTC, TaylorAkin requested changes

2023-07-13 18:49 UTC, TaylorAkin commented on web/modules/custom/lex_custom/lex_custom.module
> +use Drupal\Core\Batch\BatchBuilder;
Guess we don't need this anymore, right? @JMStewart00

2023-07-13 19:12 UTC, TaylorAkin commented
@JMStewart00 We also need the same logic for Meetings/Events as News as well

2023-07-13 22:54 UTC, JMStewart00 commented
@TaylorAkin was this in the ticket? Or is that another ticket? Didn't see that written up anywhere.

2023-07-19 03:27 UTC, TaylorAkin approved these changes

2023-07-21 03:17 UTC, merged